[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm run build"

[deploy]
startCommand = ". /root/.profile && node script/start.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
