sonar.projectKey=daler91_Hyrox-Companion
sonar.organization=daler91

sonar.sources=client/src,server,shared
sonar.exclusions=migrations/**
sonar.tests=client/src/hooks/__tests__,server/routes/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
