import { beforeEach,describe, expect, it, vi } from "vitest";

import { createMockWorkoutLog } from "../../../test/factories";
import { db } from "../../db";
import { WorkoutStorage } from "../workouts";


vi.mock("../../db", () => {
  const db: Record<string, unknown> = {
    insert: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    select: vi.fn().mockReturnValue({ from: vi.fn().mockReturnValue({ where: vi.fn().mockReturnValue([]) }) }),
  };
  // createWorkoutLog and deleteWorkoutLog both wrap their DB calls in a
  // db.transaction(tx => ...) block. The mocked transaction just invokes
  // the callback with the same `db` object so per-test mockReturnValue
  // setups on db.insert/db.update continue to apply.
  db.transaction = vi.fn((cb: (tx: typeof db) => Promise<unknown>) => cb(db));
  return { db };
});

describe("WorkoutStorage.deleteExerciseSet", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("treats a missing workout set as already removed", async () => {
    vi.spyOn(storage, "getExerciseSetOwned").mockResolvedValue(undefined);

    const result = await storage.deleteExerciseSet("workout-1", "stale-set", "user-1");

    expect(result).toBe(true);
    expect(db.delete).not.toHaveBeenCalled();
  });

  it("rejects a set owned by another workout from the nested workout route", async () => {
    vi.spyOn(storage, "getExerciseSetOwned").mockResolvedValue({
      id: "set-1",
      workoutLogId: "other-workout",
      planDayId: null,
    });

    const result = await storage.deleteExerciseSet("workout-1", "set-1", "user-1");

    expect(result).toBe(false);
    expect(db.delete).not.toHaveBeenCalled();
  });
});

describe("WorkoutStorage.deleteExerciseSetForPlanDay", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("treats a missing plan-day set as already removed", async () => {
    vi.spyOn(storage, "getExerciseSetOwned").mockResolvedValue(undefined);

    const result = await storage.deleteExerciseSetForPlanDay("plan-day-1", "stale-set", "user-1");

    expect(result).toBe(true);
    expect(db.delete).not.toHaveBeenCalled();
  });

  it("rejects a set owned by another plan day from the nested plan-day route", async () => {
    vi.spyOn(storage, "getExerciseSetOwned").mockResolvedValue({
      id: "set-1",
      workoutLogId: null,
      planDayId: "other-plan-day",
    });

    const result = await storage.deleteExerciseSetForPlanDay("plan-day-1", "set-1", "user-1");

    expect(result).toBe(false);
    expect(db.delete).not.toHaveBeenCalled();
  });
});

describe("WorkoutStorage.createWorkoutLog", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("should create a workout log successfully", async () => {
    const mockLog = { id: "w1", date: "2026-01-01", userId: "u1" };

    const returningMock = vi.fn().mockResolvedValue([mockLog]);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    vi.mocked(db.insert).mockReturnValue({ values: valuesMock });

    const result = await storage.createWorkoutLog(createMockWorkoutLog({ date: "2026-01-01", userId: "u1" }));

    expect(result).toEqual(mockLog);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(valuesMock).toHaveBeenCalledWith(expect.objectContaining({ date: "2026-01-01", userId: "u1" }));
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should create a workout log and update planDay if planDayId is provided", async () => {
    const mockLog = { id: "w2", date: "2026-01-02", userId: "u1", planDayId: "pd1" };

    const insertReturningMock = vi.fn().mockResolvedValue([mockLog]);
    const insertValuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    vi.mocked(db.insert).mockReturnValue({ values: insertValuesMock });

    const updateWhereMock = vi.fn().mockResolvedValue([]);
    const updateFromMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    const updateSetMock = vi.fn().mockReturnValue({ from: updateFromMock });
    vi.mocked(db.update).mockReturnValue({ set: updateSetMock });

    const result = await storage.createWorkoutLog(createMockWorkoutLog({ date: "2026-01-02", userId: "u1", planDayId: "pd1" }));

    expect(result).toEqual(mockLog);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
    expect(updateSetMock).toHaveBeenCalledWith({ status: "completed" });
    // Note: can't easily assert the exact `where` equality expression generated by Drizzle here without more complex mocking,
    // but verifying it was called is a good start for integration.
    expect(updateWhereMock).toHaveBeenCalled();
  });

  it("should propagate database error when insert fails", async () => {
    const dbError = new Error("Unique constraint violation");

    const returningMock = vi.fn().mockRejectedValue(dbError);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    vi.mocked(db.insert).mockReturnValue({ values: valuesMock });

    await expect(
      storage.createWorkoutLog(createMockWorkoutLog({ date: "2026-01-03", userId: "u1" }))
    ).rejects.toThrow("Unique constraint violation");

    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should propagate database error when planDay update fails after successful insert", async () => {
    const mockLog = { id: "w3", date: "2026-01-04", userId: "u1", planDayId: "pd2" };

    // Insert succeeds
    const insertReturningMock = vi.fn().mockResolvedValue([mockLog]);
    const insertValuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    vi.mocked(db.insert).mockReturnValue({ values: insertValuesMock });

    // Update fails
    const updateError = new Error("Database connection dropped during update");
    const updateWhereMock = vi.fn().mockRejectedValue(updateError);
    const updateFromMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    const updateSetMock = vi.fn().mockReturnValue({ from: updateFromMock });
    vi.mocked(db.update).mockReturnValue({ set: updateSetMock });

    await expect(
      storage.createWorkoutLog(createMockWorkoutLog({ date: "2026-01-04", userId: "u1", planDayId: "pd2" }))
    ).rejects.toThrow("Database connection dropped during update");

    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
  });

  it("should handle the edge case where returning() yields an empty array inexplicably", async () => {
    // This tests the `const [workoutLog] = ...` destructuring error path or simply undefined return.
    const returningMock = vi.fn().mockResolvedValue([]);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    vi.mocked(db.insert).mockReturnValue({ values: valuesMock });

    const result = await storage.createWorkoutLog(createMockWorkoutLog({ date: "2026-01-05", userId: "u1" }));

    // Drizzle typing for `returning()` returns an array. If it's empty, `[workoutLog]` assigns `undefined`.
    expect(result).toBeUndefined();
    expect(db.insert).toHaveBeenCalledTimes(1);
  });
});

describe("WorkoutStorage.createWorkoutLogs", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("should create multiple workout logs successfully", async () => {
    const mockLogs = [
      { id: "w1", date: "2026-01-01", userId: "u1" },
      { id: "w2", date: "2026-01-02", userId: "u1" },
    ];

    const returningMock = vi.fn().mockResolvedValue(mockLogs);
    const onConflictMock = vi.fn().mockReturnValue({ returning: returningMock });
    const valuesMock = vi.fn().mockReturnValue({ onConflictDoNothing: onConflictMock });
    vi.mocked(db.insert).mockReturnValue({ values: valuesMock });

    const logsToInsert = [
      createMockWorkoutLog({ date: "2026-01-01", userId: "u1" }),
      createMockWorkoutLog({ date: "2026-01-02", userId: "u1" }),
    ];

    const result = await storage.createWorkoutLogs(logsToInsert);

    expect(result).toEqual(mockLogs);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(valuesMock).toHaveBeenCalledWith(logsToInsert);
    expect(onConflictMock).toHaveBeenCalledTimes(1);
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should create workout logs and update planDays if planDayIds are provided", async () => {
    const mockLogs = [
      { id: "w3", date: "2026-01-03", userId: "u1", planDayId: "pd1" },
      { id: "w4", date: "2026-01-04", userId: "u1", planDayId: "pd2" },
      { id: "w5", date: "2026-01-05", userId: "u1" }, // No planDayId
    ];

    const insertReturningMock = vi.fn().mockResolvedValue(mockLogs);
    const insertOnConflictMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    const insertValuesMock = vi.fn().mockReturnValue({ onConflictDoNothing: insertOnConflictMock });
    vi.mocked(db.insert).mockReturnValue({ values: insertValuesMock });

    const updateWhereMock = vi.fn().mockResolvedValue([]);
    const updateFromMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    const updateSetMock = vi.fn().mockReturnValue({ from: updateFromMock });
    vi.mocked(db.update).mockReturnValue({ set: updateSetMock });

    const logsToInsert = [
      createMockWorkoutLog({ date: "2026-01-03", userId: "u1", planDayId: "pd1" }),
      createMockWorkoutLog({ date: "2026-01-04", userId: "u1", planDayId: "pd2" }),
      createMockWorkoutLog({ date: "2026-01-05", userId: "u1" }),
    ];

    const result = await storage.createWorkoutLogs(logsToInsert);

    expect(result).toEqual(mockLogs);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
    expect(updateSetMock).toHaveBeenCalledWith({ status: "completed" });
    expect(updateWhereMock).toHaveBeenCalled();
  });

  it("should return empty array if no logs are provided", async () => {
    const result = await storage.createWorkoutLogs([]);
    expect(result).toEqual([]);
    expect(db.insert).not.toHaveBeenCalled();
  });
});

function mockUpdateReturning(rows: unknown[]) {
  const returningMock = vi.fn().mockResolvedValue(rows);
  const whereMock = vi.fn().mockReturnValue({ returning: returningMock });
  const setMock = vi.fn().mockReturnValue({ where: whereMock });
  vi.mocked(db.update).mockReturnValue({ set: setMock } as ReturnType<typeof db.update>);
  return { returningMock, whereMock, setMock };
}

describe("WorkoutStorage.updateExerciseSetNormalized — optimistic locking (W18)", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  function mockOwned(version = 3) {
    vi.spyOn(storage, "getExerciseSetOwned").mockResolvedValue({
      id: "set-1",
      workoutLogId: "workout-1",
      planDayId: null,
      version,
    } as Awaited<ReturnType<WorkoutStorage["getExerciseSetOwned"]>>);
  }

  it("does a blind UPDATE when expectedVersion is omitted (back-compat)", async () => {
    mockOwned(3);
    const updatedRow = { id: "set-1", workoutLogId: "workout-1", version: 4, blockId: null, stepNumber: null };
    const { setMock } = mockUpdateReturning([updatedRow]);

    const result = await storage.updateExerciseSetNormalized(
      { kind: "workout", id: "workout-1", userId: "user-1" },
      "set-1",
      { reps: 10 },
    );

    expect(result).toEqual(updatedRow);
    // The SET clause always bumps version, even on blind updates.
    const setArg = setMock.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(setArg.reps).toBe(10);
    expect("version" in setArg).toBe(true);
  });

  it("bumps version and returns the new row when expectedVersion matches", async () => {
    mockOwned(3);
    const updatedRow = { id: "set-1", workoutLogId: "workout-1", version: 4, blockId: null, stepNumber: null };
    mockUpdateReturning([updatedRow]);

    const result = await storage.updateExerciseSetNormalized(
      { kind: "workout", id: "workout-1", userId: "user-1" },
      "set-1",
      { reps: 12, expectedVersion: 3 },
    );

    expect(result).toEqual(updatedRow);
  });

  it("throws AppError(CONFLICT, 409) when expectedVersion is stale", async () => {
    mockOwned(5); // server has v5; client thought it was v3
    mockUpdateReturning([]); // WHERE didn't match because version=3 ≠ 5

    await expect(
      storage.updateExerciseSetNormalized(
        { kind: "workout", id: "workout-1", userId: "user-1" },
        "set-1",
        { reps: 8, expectedVersion: 3 },
      ),
    ).rejects.toMatchObject({
      name: "AppError",
      status: 409,
      message: expect.stringContaining("modified"),
      details: { currentVersion: 5, expectedVersion: 3 },
    });
  });

  it("does NOT throw when expectedVersion is omitted and no rows match (set was deleted)", async () => {
    mockOwned(3);
    mockUpdateReturning([]); // e.g. the set was deleted between getExerciseSetOwned and the UPDATE

    const result = await storage.updateExerciseSetNormalized(
      { kind: "workout", id: "workout-1", userId: "user-1" },
      "set-1",
      { reps: 8 },
    );

    expect(result).toBeUndefined();
  });
});
