import { describe, it, expect, vi, beforeEach } from "vitest";
import { WorkoutStorage } from "../workouts";
import { db } from "../../db";


vi.mock("../../db", () => ({
  db: {
    insert: vi.fn(),
    update: vi.fn(),
    select: vi.fn().mockReturnThis(),
    from: vi.fn().mockReturnThis(),
    where: vi.fn().mockReturnThis(),
  },
}));

describe("WorkoutStorage.createWorkoutLog", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("should create a workout log successfully", async () => {
    const mockLog = { id: "w1", date: "2026-01-01", userId: "u1" };

    const returningMock = vi.fn().mockResolvedValue([mockLog]);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    (db.insert as any).mockReturnValue({ values: valuesMock });

    const result = await storage.createWorkoutLog({ date: "2026-01-01", userId: "u1" } as any);

    expect(result).toEqual(mockLog);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(valuesMock).toHaveBeenCalledWith({ date: "2026-01-01", userId: "u1" });
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should create a workout log and update planDay if planDayId is provided", async () => {
    const mockLog = { id: "w2", date: "2026-01-02", userId: "u1", planDayId: "pd1" };

    const insertReturningMock = vi.fn().mockResolvedValue([mockLog]);
    const insertValuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    (db.insert as any).mockReturnValue({ values: insertValuesMock });

    const updateWhereMock = vi.fn().mockResolvedValue([]);
    const updateSetMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    (db.update as any).mockReturnValue({ set: updateSetMock });

    const result = await storage.createWorkoutLog({ date: "2026-01-02", userId: "u1", planDayId: "pd1" } as any);

    expect(result).toEqual(mockLog);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
    expect(updateSetMock).toHaveBeenCalledWith({ status: "completed" });
    // Note: can't easily assert the exact `where` equality expression generated by Drizzle here without more complex mocking,
    // but verifying it was called is a good start for integration.
    expect(updateWhereMock).toHaveBeenCalled();
  });

  it("should propagate database error when insert fails", async () => {
    const dbError = new Error("Unique constraint violation");

    const returningMock = vi.fn().mockRejectedValue(dbError);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    (db.insert as any).mockReturnValue({ values: valuesMock });

    await expect(
      storage.createWorkoutLog({ date: "2026-01-03", userId: "u1" } as any)
    ).rejects.toThrow("Unique constraint violation");

    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should propagate database error when planDay update fails after successful insert", async () => {
    const mockLog = { id: "w3", date: "2026-01-04", userId: "u1", planDayId: "pd2" };

    // Insert succeeds
    const insertReturningMock = vi.fn().mockResolvedValue([mockLog]);
    const insertValuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    (db.insert as any).mockReturnValue({ values: insertValuesMock });

    // Update fails
    const updateError = new Error("Database connection dropped during update");
    const updateWhereMock = vi.fn().mockRejectedValue(updateError);
    const updateSetMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    (db.update as any).mockReturnValue({ set: updateSetMock });

    await expect(
      storage.createWorkoutLog({ date: "2026-01-04", userId: "u1", planDayId: "pd2" } as any)
    ).rejects.toThrow("Database connection dropped during update");

    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
  });

  it("should handle the edge case where returning() yields an empty array inexplicably", async () => {
    // This tests the `const [workoutLog] = ...` destructuring error path or simply undefined return.
    const returningMock = vi.fn().mockResolvedValue([]);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    (db.insert as any).mockReturnValue({ values: valuesMock });

    const result = await storage.createWorkoutLog({ date: "2026-01-05", userId: "u1" } as any);

    // Drizzle typing for `returning()` returns an array. If it's empty, `[workoutLog]` assigns `undefined`.
    expect(result).toBeUndefined();
    expect(db.insert).toHaveBeenCalledTimes(1);
  });
});

describe("WorkoutStorage.createWorkoutLogs", () => {
  let storage: WorkoutStorage;

  beforeEach(() => {
    storage = new WorkoutStorage();
    vi.clearAllMocks();
  });

  it("should create multiple workout logs successfully", async () => {
    const mockLogs = [
      { id: "w1", date: "2026-01-01", userId: "u1" },
      { id: "w2", date: "2026-01-02", userId: "u1" },
    ];

    const returningMock = vi.fn().mockResolvedValue(mockLogs);
    const valuesMock = vi.fn().mockReturnValue({ returning: returningMock });
    (db.insert as any).mockReturnValue({ values: valuesMock });

    const logsToInsert = [
      { date: "2026-01-01", userId: "u1" },
      { date: "2026-01-02", userId: "u1" },
    ];

    const result = await storage.createWorkoutLogs(logsToInsert as any);

    expect(result).toEqual(mockLogs);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(valuesMock).toHaveBeenCalledWith(logsToInsert);
    expect(db.update).not.toHaveBeenCalled();
  });

  it("should create workout logs and update planDays if planDayIds are provided", async () => {
    const mockLogs = [
      { id: "w3", date: "2026-01-03", userId: "u1", planDayId: "pd1" },
      { id: "w4", date: "2026-01-04", userId: "u1", planDayId: "pd2" },
      { id: "w5", date: "2026-01-05", userId: "u1" }, // No planDayId
    ];

    const insertReturningMock = vi.fn().mockResolvedValue(mockLogs);
    const insertValuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
    (db.insert as any).mockReturnValue({ values: insertValuesMock });

    const updateWhereMock = vi.fn().mockResolvedValue([]);
    const updateSetMock = vi.fn().mockReturnValue({ where: updateWhereMock });
    (db.update as any).mockReturnValue({ set: updateSetMock });

    const logsToInsert = [
      { date: "2026-01-03", userId: "u1", planDayId: "pd1" },
      { date: "2026-01-04", userId: "u1", planDayId: "pd2" },
      { date: "2026-01-05", userId: "u1" },
    ];

    const result = await storage.createWorkoutLogs(logsToInsert as any);

    expect(result).toEqual(mockLogs);
    expect(db.insert).toHaveBeenCalledTimes(1);
    expect(db.update).toHaveBeenCalledTimes(1);
    expect(updateSetMock).toHaveBeenCalledWith({ status: "completed" });
    expect(updateWhereMock).toHaveBeenCalled();
  });

  it("should return empty array if no logs are provided", async () => {
    const result = await storage.createWorkoutLogs([]);
    expect(result).toEqual([]);
    expect(db.insert).not.toHaveBeenCalled();
  });
});
