version: 2.1

orbs:
  cypress: cypress-io/cypress@6

workflows:
  build:
    jobs:
      - cypress/run:
          parallelism: 2
          start-command: npm run build && npm start
          cypress-command: 'npx cypress run --parallel --record'
