export const EXERCISE_DEFINITIONS = {
  skierg: { label: "SkiErg", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Lats", "Core"] as const },
  sled_push: { label: "Sled Push", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  sled_pull: { label: "Sled Pull", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Back", "Hamstrings"] as const },
  burpee_broad_jump: { label: "Burpee Broad Jump", category: "functional" as const, fields: ["distance", "time", "reps"] as const, muscleGroups: ["Full Body"] as const },
  rowing: { label: "Rowing", category: "functional" as const, fields: ["distance", "time"] as const, muscleGroups: ["Back", "Legs"] as const },
  farmers_carry: { label: "Farmers Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Forearms", "Core"] as const },
  sandbag_lunges: { label: "Sandbag Lunges", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  wall_balls: { label: "Wall Balls", category: "functional" as const, fields: ["reps", "time", "weight"] as const, muscleGroups: ["Quads", "Shoulders"] as const },
  shuttle_run: { label: "Shuttle Run", category: "functional" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  med_ball_slams: { label: "Med Ball Slams", category: "functional" as const, fields: ["sets", "reps", "weight", "time"] as const, muscleGroups: ["Shoulders", "Core"] as const },
  step_ups: { label: "Step Ups", category: "functional" as const, fields: ["sets", "reps", "weight", "time"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  suitcase_carry: { label: "Suitcase Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Core", "Forearms"] as const },
  overhead_carry: { label: "Overhead Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Shoulders", "Core"] as const },
  front_rack_carry: { label: "Front Rack Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Core", "Upper Back"] as const },
  yoke_carry: { label: "Yoke Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Full Body"] as const },
  sandbag_carry: { label: "Sandbag Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Full Body"] as const },
  sandbag_clean: { label: "Sandbag Clean", category: "functional" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  sandbag_to_shoulder: { label: "Sandbag to Shoulder", category: "functional" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  tire_flip: { label: "Tire Flip", category: "functional" as const, fields: ["sets", "reps", "weight", "time"] as const, muscleGroups: ["Full Body"] as const },
  rope_climb: { label: "Rope Climb", category: "functional" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Back", "Biceps", "Core"] as const },
  box_step_over: { label: "Box Step Over", category: "functional" as const, fields: ["sets", "reps", "weight", "time"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  dumbbell_thruster: { label: "Dumbbell Thruster", category: "functional" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Shoulders"] as const },
  kettlebell_thruster: { label: "Kettlebell Thruster", category: "functional" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Shoulders"] as const },
  run_1k: { label: "Run 1K", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  easy_run: { label: "Easy Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  recovery_run: { label: "Recovery Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  tempo_run: { label: "Tempo Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  interval_run: { label: "Intervals", category: "running" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  hill_repeats: { label: "Hill Repeats", category: "running" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  fartlek_run: { label: "Fartlek Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  long_run: { label: "Long Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  treadmill_run: { label: "Treadmill Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  back_squat: { label: "Back Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  front_squat: { label: "Front Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Core"] as const },
  air_squat: { label: "Air Squat", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  overhead_squat: { label: "Overhead Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Shoulders", "Core"] as const },
  zercher_squat: { label: "Zercher Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Core", "Back"] as const },
  pistol_squat: { label: "Pistol Squat", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Quads", "Glutes", "Core"] as const },
  split_squat: { label: "Split Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  cossack_squat: { label: "Cossack Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Adductors", "Glutes", "Quads"] as const },
  belt_squat: { label: "Belt Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  box_squat: { label: "Box Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  smith_machine_squat: { label: "Smith Machine Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  deadlift: { label: "Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Back"] as const },
  trap_bar_deadlift: { label: "Trap Bar Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes", "Back"] as const },
  sumo_deadlift: { label: "Sumo Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings", "Back"] as const },
  stiff_leg_deadlift: { label: "Stiff Leg Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes", "Back"] as const },
  rack_pull: { label: "Rack Pull", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Hamstrings", "Glutes"] as const },
  deficit_deadlift: { label: "Deficit Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes", "Back"] as const },
  romanian_deadlift: { label: "Romanian Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes"] as const },
  good_morning: { label: "Good Morning", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes", "Back"] as const },
  bench_press: { label: "Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  incline_bench_press: { label: "Incline Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Shoulders"] as const },
  decline_bench_press: { label: "Decline Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  close_grip_bench_press: { label: "Close Grip Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  incline_dumbbell_bench_press: { label: "Incline Dumbbell Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Shoulders"] as const },
  dumbbell_fly: { label: "Dumbbell Fly", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest"] as const },
  floor_press: { label: "Floor Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  smith_machine_bench_press: { label: "Smith Machine Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  dumbbell_pullover: { label: "Dumbbell Pullover", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Lats"] as const },
  push_up: { label: "Push-up", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Chest", "Triceps", "Core"] as const },
  handstand_push_up: { label: "Handstand Push-up", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Shoulders", "Triceps", "Core"] as const },
  pike_push_up: { label: "Pike Push-up", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  overhead_press: { label: "Overhead Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  push_press: { label: "Push Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  landmine_press: { label: "Landmine Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Chest", "Core"] as const },
  pull_up: { label: "Pull-ups", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  chin_up: { label: "Chin-ups", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  assisted_pull_up: { label: "Assisted Pull-up", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  inverted_row: { label: "Inverted Row", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Back", "Biceps", "Core"] as const },
  lat_pulldown: { label: "Lat Pulldown", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  straight_arm_pulldown: { label: "Straight Arm Pulldown", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Lats"] as const },
  bent_over_row: { label: "Bent Over Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  pendlay_row: { label: "Pendlay Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  machine_row: { label: "Machine Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  landmine_row: { label: "Landmine Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  single_arm_dumbbell_row: { label: "Single Arm Dumbbell Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  lunges: { label: "Lunges", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  reverse_lunge: { label: "Reverse Lunge", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  bulgarian_split_squat: { label: "Bulgarian Split Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  hip_thrust: { label: "Hip Thrust", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  single_leg_rdl: { label: "Single Leg RDL", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes"] as const },
  barbell_thruster: { label: "Barbell Thruster", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Shoulders"] as const },
  goblet_squat: { label: "Goblet Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Core"] as const },
  dumbbell_snatch: { label: "Dumbbell Snatch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Core"] as const },
  dumbbell_bench_press: { label: "Dumbbell Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  seated_cable_row: { label: "Seated Cable Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  chest_supported_row: { label: "Chest Supported Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  leg_press: { label: "Leg Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  hack_squat: { label: "Hack Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  leg_extension: { label: "Leg Extension", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads"] as const },
  hamstring_curl: { label: "Hamstring Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings"] as const },
  calf_raise: { label: "Calf Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Calves"] as const },
  seated_calf_raise: { label: "Seated Calf Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Calves"] as const },
  standing_calf_raise: { label: "Standing Calf Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Calves"] as const },
  tibialis_raise: { label: "Tibialis Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Tibialis", "Ankles"] as const },
  dip: { label: "Dips", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  assisted_dip: { label: "Assisted Dip", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  ring_dip: { label: "Ring Dip", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps", "Core"] as const },
  bench_dip: { label: "Bench Dip", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Triceps", "Chest"] as const },
  triceps_pushdown: { label: "Triceps Pushdown", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Triceps"] as const },
  triceps_kickback: { label: "Triceps Kickback", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Triceps"] as const },
  rope_triceps_pushdown: { label: "Rope Triceps Pushdown", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Triceps"] as const },
  skull_crusher: { label: "Skull Crusher", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Triceps"] as const },
  overhead_triceps_extension: { label: "Overhead Triceps Extension", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Triceps"] as const },
  barbell_curl: { label: "Barbell Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  dumbbell_curl: { label: "Dumbbell Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  hammer_curl: { label: "Hammer Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps", "Forearms"] as const },
  preacher_curl: { label: "Preacher Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  cable_curl: { label: "Cable Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  concentration_curl: { label: "Concentration Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  incline_dumbbell_curl: { label: "Incline Dumbbell Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps"] as const },
  reverse_curl: { label: "Reverse Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Biceps", "Forearms"] as const },
  wrist_curl: { label: "Wrist Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Forearms"] as const },
  reverse_wrist_curl: { label: "Reverse Wrist Curl", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Forearms"] as const },
  face_pull: { label: "Face Pull", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Rear Delts", "Upper Back"] as const },
  cable_fly: { label: "Cable Fly", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest"] as const },
  pec_deck: { label: "Pec Deck", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest"] as const },
  lateral_raise: { label: "Lateral Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders"] as const },
  cable_lateral_raise: { label: "Cable Lateral Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders"] as const },
  machine_lateral_raise: { label: "Machine Lateral Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders"] as const },
  front_raise: { label: "Front Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders"] as const },
  rear_delt_fly: { label: "Rear Delt Fly", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Rear Delts"] as const },
  reverse_pec_deck: { label: "Reverse Pec Deck", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Rear Delts", "Upper Back"] as const },
  cable_rear_delt_fly: { label: "Cable Rear Delt Fly", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Rear Delts"] as const },
  band_pull_apart: { label: "Band Pull Apart", category: "strength" as const, fields: ["sets", "reps"] as const, muscleGroups: ["Rear Delts", "Upper Back"] as const },
  seated_dumbbell_press: { label: "Seated Dumbbell Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  arnold_press: { label: "Arnold Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  machine_shoulder_press: { label: "Machine Shoulder Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  barbell_shrug: { label: "Barbell Shrug", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Traps", "Upper Back"] as const },
  upright_row: { label: "Upright Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Traps"] as const },
  t_bar_row: { label: "T-Bar Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  single_arm_cable_row: { label: "Single Arm Cable Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  high_row_machine: { label: "High Row Machine", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  chest_press_machine: { label: "Chest Press Machine", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  pullover_machine: { label: "Pullover Machine", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Lats"] as const },
  glute_bridge: { label: "Glute Bridge", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  nordic_hamstring_curl: { label: "Nordic Hamstring Curl", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Hamstrings"] as const },
  glute_ham_raise: { label: "Glute Ham Raise", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes"] as const },
  cable_pull_through: { label: "Cable Pull Through", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  hip_abduction_machine: { label: "Hip Abduction Machine", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hip Abductors"] as const },
  hip_adduction_machine: { label: "Hip Adduction Machine", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Adductors"] as const },
  glute_kickback: { label: "Glute Kickback", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes"] as const },
  donkey_kick: { label: "Donkey Kick", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes"] as const },
  frog_pump: { label: "Frog Pump", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes"] as const },
  clamshell: { label: "Clamshell", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Glutes", "Hip Abductors"] as const },
  sissy_squat: { label: "Sissy Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads"] as const },
  pendulum_squat: { label: "Pendulum Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  cable_crunch: { label: "Cable Crunch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Core"] as const },
  side_plank: { label: "Side Plank", category: "strength" as const, fields: ["sets", "time"] as const, muscleGroups: ["Core", "Obliques"] as const },
  ab_wheel_rollout: { label: "Ab Wheel Rollout", category: "strength" as const, fields: ["sets", "reps"] as const, muscleGroups: ["Core"] as const },
  pallof_press: { label: "Pallof Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Core", "Obliques"] as const },
  sit_up: { label: "Sit-up", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  crunch: { label: "Crunch", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  reverse_crunch: { label: "Reverse Crunch", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  bicycle_crunch: { label: "Bicycle Crunch", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core", "Obliques"] as const },
  russian_twist: { label: "Russian Twist", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  dead_bug: { label: "Dead Bug", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  bird_dog: { label: "Bird Dog", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core", "Lower Back"] as const },
  back_extension: { label: "Back Extension", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Lower Back", "Glutes", "Hamstrings"] as const },
  plank: { label: "Plank", category: "strength" as const, fields: ["sets", "time"] as const, muscleGroups: ["Core"] as const },
  hanging_leg_raise: { label: "Hanging Leg Raise", category: "strength" as const, fields: ["sets", "reps"] as const, muscleGroups: ["Core", "Hip Flexors"] as const },
  lying_leg_raise: { label: "Lying Leg Raise", category: "strength" as const, fields: ["sets", "reps"] as const, muscleGroups: ["Core", "Hip Flexors"] as const },
  toes_to_bar: { label: "Toes to Bar", category: "strength" as const, fields: ["sets", "reps"] as const, muscleGroups: ["Core", "Hip Flexors"] as const },
  v_up: { label: "V-up", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core"] as const },
  hollow_hold: { label: "Hollow Hold", category: "strength" as const, fields: ["sets", "time"] as const, muscleGroups: ["Core"] as const },
  flutter_kicks: { label: "Flutter Kicks", category: "strength" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core", "Hip Flexors"] as const },
  clean: { label: "Clean", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  power_clean: { label: "Power Clean", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  hang_clean: { label: "Hang Clean", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  clean_and_jerk: { label: "Clean and Jerk", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  jerk: { label: "Jerk", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Legs", "Core"] as const },
  split_jerk: { label: "Split Jerk", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Legs", "Core"] as const },
  snatch: { label: "Snatch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  power_snatch: { label: "Power Snatch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  hang_snatch: { label: "Hang Snatch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  turkish_get_up: { label: "Turkish Get-up", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Core", "Shoulders"] as const },
  kettlebell_clean: { label: "Kettlebell Clean", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  kettlebell_snatch: { label: "Kettlebell Snatch", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Full Body"] as const },
  kettlebell_press: { label: "Kettlebell Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  burpees: { label: "Burpees", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Full Body"] as const },
  box_jumps: { label: "Box Jumps", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Quads", "Calves"] as const },
  devil_press: { label: "Devil Press", category: "conditioning" as const, fields: ["sets", "reps", "weight", "time"] as const, muscleGroups: ["Full Body"] as const },
  walking: { label: "Walking", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  incline_walk: { label: "Incline Walk", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  hiking: { label: "Hiking", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  rucking: { label: "Rucking", category: "conditioning" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Legs", "Back", "Cardio"] as const },
  cycling: { label: "Cycling", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  bike_erg: { label: "BikeErg", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  elliptical: { label: "Elliptical", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  stair_climber: { label: "Stair Climber", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Quads", "Glutes", "Cardio"] as const },
  swimming: { label: "Swimming", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Full Body", "Cardio"] as const },
  sprints: { label: "Sprints", category: "conditioning" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  bear_crawl: { label: "Bear Crawl", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Full Body"] as const },
  crab_walk: { label: "Crab Walk", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Shoulders", "Core", "Glutes"] as const },
  jumping_jacks: { label: "Jumping Jacks", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Full Body", "Cardio"] as const },
  high_knees: { label: "High Knees", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  butt_kicks: { label: "Butt Kicks", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Hamstrings", "Cardio"] as const },
  assault_bike: { label: "Assault Bike", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  stationary_bike: { label: "Stationary Bike", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  kettlebell_swings: { label: "KB Swings", category: "conditioning" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  battle_ropes: { label: "Battle Ropes", category: "conditioning" as const, fields: ["sets", "time"] as const, muscleGroups: ["Shoulders", "Core"] as const },
  walking_lunges: { label: "Walking Lunges", category: "conditioning" as const, fields: ["distance", "reps", "time", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  echo_bike: { label: "Echo Bike", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  ski_erg_intervals: { label: "SkiErg Intervals", category: "conditioning" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Lats", "Core"] as const },
  jump_rope: { label: "Jump Rope", category: "conditioning" as const, fields: ["time", "reps"] as const, muscleGroups: ["Calves", "Cardio"] as const },
  mountain_climbers: { label: "Mountain Climbers", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Core", "Cardio"] as const },
  rowing_intervals: { label: "Rowing Intervals", category: "conditioning" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Back", "Cardio"] as const },
  treadmill_intervals: { label: "Treadmill Intervals", category: "conditioning" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  emom: { label: "EMOM", category: "conditioning" as const, fields: ["time", "reps", "sets"] as const, muscleGroups: ["Full Body"] as const },
  amrap: { label: "AMRAP", category: "conditioning" as const, fields: ["time", "reps", "sets"] as const, muscleGroups: ["Full Body"] as const },
  custom: { label: "Custom", category: "conditioning" as const, fields: ["sets", "reps", "weight", "distance", "time"] as const, muscleGroups: [] as const },
} as const;

export type ExerciseName = keyof typeof EXERCISE_DEFINITIONS;
export const exerciseNames = Object.keys(EXERCISE_DEFINITIONS) as ExerciseName[];

export const MOVEMENT_PATTERNS = [
  { pattern: "squat", label: "Squat pattern" },
  { pattern: "hinge", label: "Hinge pattern" },
  { pattern: "horizontal_push", label: "Horizontal push" },
  { pattern: "vertical_push", label: "Vertical push" },
  { pattern: "horizontal_pull", label: "Horizontal pull" },
  { pattern: "vertical_pull", label: "Vertical pull" },
  { pattern: "lunge_split_squat", label: "Lunge / split squat" },
  { pattern: "carry", label: "Carry" },
  { pattern: "core_flexion", label: "Core flexion" },
  { pattern: "core_anti_rotation", label: "Core anti-rotation" },
] as const;

export type MovementPattern = (typeof MOVEMENT_PATTERNS)[number]["pattern"];

export const EXERCISE_MOVEMENT_PATTERNS = {
  skierg: ["vertical_pull"],
  sled_push: ["squat"],
  sled_pull: ["hinge", "horizontal_pull"],
  rowing: ["horizontal_pull"],
  farmers_carry: ["carry"],
  sandbag_lunges: ["lunge_split_squat"],
  wall_balls: ["squat", "vertical_push"],
  med_ball_slams: ["hinge", "core_flexion"],
  step_ups: ["squat", "lunge_split_squat"],
  suitcase_carry: ["carry", "core_anti_rotation"],
  overhead_carry: ["carry", "core_anti_rotation"],
  front_rack_carry: ["carry"],
  yoke_carry: ["carry"],
  sandbag_carry: ["carry"],
  sandbag_clean: ["hinge"],
  sandbag_to_shoulder: ["hinge"],
  tire_flip: ["hinge"],
  rope_climb: ["vertical_pull"],
  box_step_over: ["squat", "lunge_split_squat"],
  dumbbell_thruster: ["squat", "vertical_push"],
  kettlebell_thruster: ["squat", "vertical_push"],
  back_squat: ["squat"],
  front_squat: ["squat"],
  air_squat: ["squat"],
  overhead_squat: ["squat", "vertical_push", "core_anti_rotation"],
  zercher_squat: ["squat"],
  pistol_squat: ["squat", "lunge_split_squat"],
  split_squat: ["lunge_split_squat"],
  cossack_squat: ["squat", "lunge_split_squat"],
  belt_squat: ["squat"],
  box_squat: ["squat"],
  smith_machine_squat: ["squat"],
  deadlift: ["hinge"],
  trap_bar_deadlift: ["squat", "hinge"],
  sumo_deadlift: ["hinge"],
  stiff_leg_deadlift: ["hinge"],
  rack_pull: ["hinge"],
  deficit_deadlift: ["hinge"],
  romanian_deadlift: ["hinge"],
  good_morning: ["hinge"],
  bench_press: ["horizontal_push"],
  incline_bench_press: ["horizontal_push"],
  decline_bench_press: ["horizontal_push"],
  close_grip_bench_press: ["horizontal_push"],
  incline_dumbbell_bench_press: ["horizontal_push"],
  dumbbell_fly: ["horizontal_push"],
  floor_press: ["horizontal_push"],
  smith_machine_bench_press: ["horizontal_push"],
  dumbbell_pullover: ["horizontal_pull"],
  push_up: ["horizontal_push"],
  handstand_push_up: ["vertical_push"],
  pike_push_up: ["vertical_push"],
  overhead_press: ["vertical_push"],
  push_press: ["vertical_push"],
  landmine_press: ["vertical_push", "core_anti_rotation"],
  pull_up: ["vertical_pull"],
  chin_up: ["vertical_pull"],
  assisted_pull_up: ["vertical_pull"],
  inverted_row: ["horizontal_pull"],
  lat_pulldown: ["vertical_pull"],
  straight_arm_pulldown: ["vertical_pull"],
  bent_over_row: ["horizontal_pull"],
  pendlay_row: ["horizontal_pull"],
  machine_row: ["horizontal_pull"],
  landmine_row: ["horizontal_pull"],
  single_arm_dumbbell_row: ["horizontal_pull", "core_anti_rotation"],
  lunges: ["lunge_split_squat"],
  reverse_lunge: ["lunge_split_squat"],
  bulgarian_split_squat: ["lunge_split_squat"],
  hip_thrust: ["hinge"],
  single_leg_rdl: ["hinge", "lunge_split_squat"],
  barbell_thruster: ["squat", "vertical_push"],
  goblet_squat: ["squat"],
  dumbbell_snatch: ["hinge", "vertical_push"],
  dumbbell_bench_press: ["horizontal_push"],
  seated_cable_row: ["horizontal_pull"],
  chest_supported_row: ["horizontal_pull"],
  leg_press: ["squat"],
  hack_squat: ["squat"],
  leg_extension: ["squat"],
  hamstring_curl: ["hinge"],
  dip: ["horizontal_push"],
  assisted_dip: ["horizontal_push"],
  ring_dip: ["horizontal_push", "core_anti_rotation"],
  bench_dip: ["horizontal_push"],
  face_pull: ["horizontal_pull"],
  cable_fly: ["horizontal_push"],
  pec_deck: ["horizontal_push"],
  rear_delt_fly: ["horizontal_pull"],
  reverse_pec_deck: ["horizontal_pull"],
  cable_rear_delt_fly: ["horizontal_pull"],
  band_pull_apart: ["horizontal_pull"],
  seated_dumbbell_press: ["vertical_push"],
  arnold_press: ["vertical_push"],
  machine_shoulder_press: ["vertical_push"],
  t_bar_row: ["horizontal_pull"],
  single_arm_cable_row: ["horizontal_pull", "core_anti_rotation"],
  high_row_machine: ["horizontal_pull"],
  chest_press_machine: ["horizontal_push"],
  pullover_machine: ["vertical_pull"],
  glute_bridge: ["hinge"],
  nordic_hamstring_curl: ["hinge"],
  glute_ham_raise: ["hinge"],
  cable_pull_through: ["hinge"],
  glute_kickback: ["hinge"],
  donkey_kick: ["hinge"],
  frog_pump: ["hinge"],
  sissy_squat: ["squat"],
  pendulum_squat: ["squat"],
  cable_crunch: ["core_flexion"],
  side_plank: ["core_anti_rotation"],
  ab_wheel_rollout: ["core_flexion", "core_anti_rotation"],
  pallof_press: ["core_anti_rotation"],
  sit_up: ["core_flexion"],
  crunch: ["core_flexion"],
  reverse_crunch: ["core_flexion"],
  bicycle_crunch: ["core_flexion"],
  russian_twist: ["core_flexion", "core_anti_rotation"],
  dead_bug: ["core_anti_rotation"],
  bird_dog: ["core_anti_rotation"],
  back_extension: ["hinge"],
  plank: ["core_anti_rotation"],
  hanging_leg_raise: ["core_flexion"],
  lying_leg_raise: ["core_flexion"],
  toes_to_bar: ["core_flexion"],
  v_up: ["core_flexion"],
  hollow_hold: ["core_anti_rotation"],
  flutter_kicks: ["core_flexion"],
  clean: ["hinge"],
  power_clean: ["hinge"],
  hang_clean: ["hinge"],
  clean_and_jerk: ["hinge", "vertical_push"],
  jerk: ["vertical_push"],
  split_jerk: ["vertical_push", "lunge_split_squat"],
  snatch: ["hinge", "vertical_push"],
  power_snatch: ["hinge", "vertical_push"],
  hang_snatch: ["hinge", "vertical_push"],
  turkish_get_up: ["vertical_push", "core_anti_rotation"],
  kettlebell_clean: ["hinge"],
  kettlebell_snatch: ["hinge", "vertical_push"],
  kettlebell_press: ["vertical_push"],
  burpees: ["squat", "horizontal_push"],
  box_jumps: ["squat"],
  devil_press: ["hinge", "vertical_push"],
  rucking: ["carry"],
  stair_climber: ["squat"],
  bear_crawl: ["horizontal_push", "core_anti_rotation"],
  crab_walk: ["horizontal_push", "core_anti_rotation"],
  kettlebell_swings: ["hinge"],
  battle_ropes: ["horizontal_pull"],
  walking_lunges: ["lunge_split_squat"],
  ski_erg_intervals: ["vertical_pull"],
  mountain_climbers: ["core_flexion"],
  rowing_intervals: ["horizontal_pull"],
} satisfies Partial<Record<ExerciseName, readonly MovementPattern[]>>;

export const EXERCISE_NAME_ALIASES: Record<string, ExerciseName> = {
  rdl: "romanian_deadlift",
  romanian_deadlifts: "romanian_deadlift",
  air_squats: "air_squat",
  overhead_squats: "overhead_squat",
  zercher_squats: "zercher_squat",
  pistols: "pistol_squat",
  pistol_squats: "pistol_squat",
  split_squats: "split_squat",
  cossack_squats: "cossack_squat",
  belt_squats: "belt_squat",
  stiff_leg_deadlifts: "stiff_leg_deadlift",
  sldl: "stiff_leg_deadlift",
  rack_pulls: "rack_pull",
  deficit_deadlifts: "deficit_deadlift",
  pushups: "push_up",
  push_ups: "push_up",
  handstand_pushups: "handstand_push_up",
  handstand_push_ups: "handstand_push_up",
  hspu: "handstand_push_up",
  pike_pushups: "pike_push_up",
  pike_push_ups: "pike_push_up",
  floor_presses: "floor_press",
  smith_bench: "smith_machine_bench_press",
  smith_machine_bench: "smith_machine_bench_press",
  db_bench: "dumbbell_bench_press",
  dumbbell_bench: "dumbbell_bench_press",
  incline_db_bench: "incline_dumbbell_bench_press",
  incline_dumbbell_bench: "incline_dumbbell_bench_press",
  db_pullover: "dumbbell_pullover",
  dumbbell_pullovers: "dumbbell_pullover",
  db_fly: "dumbbell_fly",
  dumbbell_flys: "dumbbell_fly",
  dumbbell_flies: "dumbbell_fly",
  close_grip_bench: "close_grip_bench_press",
  ohp: "overhead_press",
  strict_press: "overhead_press",
  landmine_presses: "landmine_press",
  lat_pulldowns: "lat_pulldown",
  lat_pull_down: "lat_pulldown",
  pullups: "pull_up",
  chinup: "chin_up",
  chinups: "chin_up",
  chin_ups: "chin_up",
  assisted_pullups: "assisted_pull_up",
  assisted_pull_ups: "assisted_pull_up",
  inverted_rows: "inverted_row",
  straight_arm_lat_pulldown: "straight_arm_pulldown",
  straight_arm_pulldowns: "straight_arm_pulldown",
  seated_row: "seated_cable_row",
  cable_row: "seated_cable_row",
  chest_supported_rows: "chest_supported_row",
  pendlay_rows: "pendlay_row",
  machine_rows: "machine_row",
  landmine_rows: "landmine_row",
  trap_bar_dl: "trap_bar_deadlift",
  hex_bar_deadlift: "trap_bar_deadlift",
  hex_bar_dl: "trap_bar_deadlift",
  sumo_dl: "sumo_deadlift",
  sumo_deadlifts: "sumo_deadlift",
  good_mornings: "good_morning",
  box_squats: "box_squat",
  smith_squat: "smith_machine_squat",
  smith_machine_squats: "smith_machine_squat",
  legpress: "leg_press",
  hacksquat: "hack_squat",
  leg_extensions: "leg_extension",
  hamstring_curls: "hamstring_curl",
  calf_raises: "calf_raise",
  seated_calf_raises: "seated_calf_raise",
  standing_calf_raises: "standing_calf_raise",
  tib_raises: "tibialis_raise",
  tibialis_raises: "tibialis_raise",
  reverse_lunges: "reverse_lunge",
  dips: "dip",
  assisted_dips: "assisted_dip",
  ring_dips: "ring_dip",
  bench_dips: "bench_dip",
  tricep_pushdown: "triceps_pushdown",
  tricep_pushdowns: "triceps_pushdown",
  tricep_kickback: "triceps_kickback",
  tricep_kickbacks: "triceps_kickback",
  triceps_kickbacks: "triceps_kickback",
  rope_tricep_pushdown: "rope_triceps_pushdown",
  rope_tricep_pushdowns: "rope_triceps_pushdown",
  rope_pushdown: "rope_triceps_pushdown",
  rope_pushdowns: "rope_triceps_pushdown",
  skullcrushers: "skull_crusher",
  skull_crushers: "skull_crusher",
  overhead_tricep_extension: "overhead_triceps_extension",
  overhead_tricep_extensions: "overhead_triceps_extension",
  overhead_triceps_extensions: "overhead_triceps_extension",
  bb_curl: "barbell_curl",
  curls: "dumbbell_curl",
  hammer_curls: "hammer_curl",
  preacher_curls: "preacher_curl",
  cable_curls: "cable_curl",
  concentration_curls: "concentration_curl",
  incline_db_curl: "incline_dumbbell_curl",
  incline_db_curls: "incline_dumbbell_curl",
  reverse_curls: "reverse_curl",
  wrist_curls: "wrist_curl",
  reverse_wrist_curls: "reverse_wrist_curl",
  db_row: "single_arm_dumbbell_row",
  arnold_presses: "arnold_press",
  cable_lateral_raises: "cable_lateral_raise",
  machine_lateral_raises: "machine_lateral_raise",
  front_raises: "front_raise",
  shrugs: "barbell_shrug",
  barbell_shrugs: "barbell_shrug",
  tbar_row: "t_bar_row",
  machine_chest_press: "chest_press_machine",
  shoulder_press_machine: "machine_shoulder_press",
  lat_raise: "lateral_raise",
  rear_delt_raise: "rear_delt_fly",
  reverse_pec_decks: "reverse_pec_deck",
  cable_rear_delt_flys: "cable_rear_delt_fly",
  cable_rear_delt_flies: "cable_rear_delt_fly",
  band_pull_aparts: "band_pull_apart",
  high_rows: "high_row_machine",
  high_row: "high_row_machine",
  pullover_machines: "pullover_machine",
  abductor_machine: "hip_abduction_machine",
  hip_abductor: "hip_abduction_machine",
  hip_abductor_machine: "hip_abduction_machine",
  adductor_machine: "hip_adduction_machine",
  hip_adductor: "hip_adduction_machine",
  hip_adductor_machine: "hip_adduction_machine",
  glute_kickbacks: "glute_kickback",
  cable_kickback: "glute_kickback",
  cable_kickbacks: "glute_kickback",
  donkey_kicks: "donkey_kick",
  frog_pumps: "frog_pump",
  clamshells: "clamshell",
  sissy_squats: "sissy_squat",
  pendulum_squats: "pendulum_squat",
  nordics: "nordic_hamstring_curl",
  nordic_curl: "nordic_hamstring_curl",
  nordic_curls: "nordic_hamstring_curl",
  ghr: "glute_ham_raise",
  glute_ham_raises: "glute_ham_raise",
  pull_through: "cable_pull_through",
  pull_throughs: "cable_pull_through",
  cable_pull_throughs: "cable_pull_through",
  ab_crunch: "cable_crunch",
  situps: "sit_up",
  sit_ups: "sit_up",
  crunches: "crunch",
  reverse_crunches: "reverse_crunch",
  bicycle_crunches: "bicycle_crunch",
  russian_twists: "russian_twist",
  dead_bugs: "dead_bug",
  bird_dogs: "bird_dog",
  back_extensions: "back_extension",
  hyperextension: "back_extension",
  hyperextensions: "back_extension",
  side_planks: "side_plank",
  ab_wheel: "ab_wheel_rollout",
  ab_rollout: "ab_wheel_rollout",
  ab_rollouts: "ab_wheel_rollout",
  pallof_presses: "pallof_press",
  hanging_leg_raises: "hanging_leg_raise",
  lying_leg_raises: "lying_leg_raise",
  toes_to_bars: "toes_to_bar",
  t2b: "toes_to_bar",
  vups: "v_up",
  v_ups: "v_up",
  hollow_holds: "hollow_hold",
  flutter_kick: "flutter_kicks",
  rope_jump: "jump_rope",
  row_intervals: "rowing_intervals",
  bikeerg: "bike_erg",
  bike_ergometer: "bike_erg",
  stairmaster: "stair_climber",
  stair_climbers: "stair_climber",
  ruck: "rucking",
  bear_crawls: "bear_crawl",
  crab_walks: "crab_walk",
  jumping_jack: "jumping_jacks",
  high_knee: "high_knees",
  butt_kick: "butt_kicks",
  suitcase_carries: "suitcase_carry",
  overhead_carries: "overhead_carry",
  front_rack_carries: "front_rack_carry",
  yoke_walk: "yoke_carry",
  yoke_walks: "yoke_carry",
  sandbag_carries: "sandbag_carry",
  sandbag_cleans: "sandbag_clean",
  sandbag_shouldering: "sandbag_to_shoulder",
  tire_flips: "tire_flip",
  rope_climbs: "rope_climb",
  box_step_overs: "box_step_over",
  db_thruster: "dumbbell_thruster",
  db_thrusters: "dumbbell_thruster",
  kb_thruster: "kettlebell_thruster",
  kb_thrusters: "kettlebell_thruster",
  clean_jerk: "clean_and_jerk",
  c_j: "clean_and_jerk",
  power_cleans: "power_clean",
  hang_cleans: "hang_clean",
  split_jerks: "split_jerk",
  power_snatches: "power_snatch",
  hang_snatches: "hang_snatch",
  tgu: "turkish_get_up",
  turkish_getup: "turkish_get_up",
  kb_clean: "kettlebell_clean",
  kb_cleans: "kettlebell_clean",
  kb_snatch: "kettlebell_snatch",
  kb_snatches: "kettlebell_snatch",
  kb_press: "kettlebell_press",
  kb_presses: "kettlebell_press",
  devil_presses: "devil_press",
};

export function normalizeExerciseName(raw: string): ExerciseName | null {
  const lower = raw.trim().toLowerCase();
  let normalized = "";
  let previousWasSeparator = false;

  for (const char of lower) {
    if ((char >= "a" && char <= "z") || (char >= "0" && char <= "9")) {
      normalized += char;
      previousWasSeparator = false;
      continue;
    }

    if (char === "'" || char === "’") continue;

    if (!previousWasSeparator && normalized.length > 0) {
      normalized += "_";
      previousWasSeparator = true;
    }
  }

  if (normalized.endsWith("_")) normalized = normalized.slice(0, -1);
  if (!normalized) return null;
  if (normalized in EXERCISE_DEFINITIONS) return normalized as ExerciseName;
  return EXERCISE_NAME_ALIASES[normalized] ?? null;
}

export function getExerciseMovementPatterns(exerciseName: string): readonly MovementPattern[] {
  const normalizedExerciseName = normalizeExerciseName(exerciseName);
  if (!normalizedExerciseName || !(normalizedExerciseName in EXERCISE_MOVEMENT_PATTERNS)) {
    return [];
  }

  return EXERCISE_MOVEMENT_PATTERNS[
    normalizedExerciseName as keyof typeof EXERCISE_MOVEMENT_PATTERNS
  ];
}
