export const EXERCISE_DEFINITIONS = {
  skierg: { label: "SkiErg", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Lats", "Core"] as const },
  sled_push: { label: "Sled Push", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  sled_pull: { label: "Sled Pull", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Back", "Hamstrings"] as const },
  burpee_broad_jump: { label: "Burpee Broad Jump", category: "functional" as const, fields: ["distance", "time", "reps"] as const, muscleGroups: ["Full Body"] as const },
  rowing: { label: "Rowing", category: "functional" as const, fields: ["distance", "time"] as const, muscleGroups: ["Back", "Legs"] as const },
  farmers_carry: { label: "Farmers Carry", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Forearms", "Core"] as const },
  sandbag_lunges: { label: "Sandbag Lunges", category: "functional" as const, fields: ["distance", "time", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  wall_balls: { label: "Wall Balls", category: "functional" as const, fields: ["reps", "time", "weight"] as const, muscleGroups: ["Quads", "Shoulders"] as const },
  easy_run: { label: "Easy Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  tempo_run: { label: "Tempo Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  interval_run: { label: "Intervals", category: "running" as const, fields: ["distance", "time", "sets"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  long_run: { label: "Long Run", category: "running" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  back_squat: { label: "Back Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  front_squat: { label: "Front Squat", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Core"] as const },
  deadlift: { label: "Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Back"] as const },
  romanian_deadlift: { label: "Romanian Deadlift", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Hamstrings", "Glutes"] as const },
  bench_press: { label: "Bench Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Chest", "Triceps"] as const },
  overhead_press: { label: "Overhead Press", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Shoulders", "Triceps"] as const },
  pull_up: { label: "Pull-ups", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  bent_over_row: { label: "Bent Over Row", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Back", "Biceps"] as const },
  lunges: { label: "Lunges", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Quads", "Glutes"] as const },
  hip_thrust: { label: "Hip Thrust", category: "strength" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  burpees: { label: "Burpees", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Full Body"] as const },
  box_jumps: { label: "Box Jumps", category: "conditioning" as const, fields: ["sets", "reps", "time"] as const, muscleGroups: ["Quads", "Calves"] as const },
  assault_bike: { label: "Assault Bike", category: "conditioning" as const, fields: ["distance", "time"] as const, muscleGroups: ["Legs", "Cardio"] as const },
  kettlebell_swings: { label: "KB Swings", category: "conditioning" as const, fields: ["sets", "reps", "weight"] as const, muscleGroups: ["Glutes", "Hamstrings"] as const },
  battle_ropes: { label: "Battle Ropes", category: "conditioning" as const, fields: ["sets", "time"] as const, muscleGroups: ["Shoulders", "Core"] as const },
  custom: { label: "Custom", category: "conditioning" as const, fields: ["sets", "reps", "weight", "distance", "time"] as const, muscleGroups: [] as const },
} as const;

export type ExerciseName = keyof typeof EXERCISE_DEFINITIONS;
export const exerciseNames = Object.keys(EXERCISE_DEFINITIONS) as ExerciseName[];
