export const samplePlanDays = [
  { week: 1, day: "Monday", focus: "Running Base", main: "5km easy run at conversational pace", accessory: "Core circuit: 3x(20 plank, 15 dead bugs, 20 bird dogs)", notes: "Focus on form and breathing" },
  { week: 1, day: "Tuesday", focus: "Strength", main: "4x8 goblet squats, 4x8 Romanian deadlifts, 4x8 push-ups", accessory: "3x20 walking lunges", notes: "Keep weights moderate" },
  { week: 1, day: "Wednesday", focus: "SkiErg", main: "5x500m SkiErg with 90s rest", accessory: "3x10 lat pulldowns, 3x12 face pulls", notes: "Focus on full arm extension" },
  { week: 1, day: "Thursday", focus: "Active Recovery", main: "30min easy bike or swim", accessory: "Foam rolling and stretching", notes: null },
  { week: 1, day: "Friday", focus: "Sled Work", main: "6x50m sled push (moderate weight), 6x50m sled pull", accessory: "3x10 KB swings", notes: "Short rest between sets" },
  { week: 1, day: "Saturday", focus: "Long Run", main: "8km steady run", accessory: null, notes: "Build aerobic base" },
  { week: 1, day: "Sunday", focus: "Rest", main: "Complete rest or light walk", accessory: null, notes: null },

  { week: 2, day: "Monday", focus: "Running Intervals", main: "6x400m at 5K pace with 200m jog recovery", accessory: "Core: 3x(30s plank, 20 Russian twists)", notes: null },
  { week: 2, day: "Tuesday", focus: "Upper Strength", main: "5x5 bench press, 5x5 barbell rows, 3x8 overhead press", accessory: "3x15 tricep dips, 3x12 bicep curls", notes: null },
  { week: 2, day: "Wednesday", focus: "Rowing", main: "4x1000m row with 2min rest", accessory: "3x12 seated cable rows", notes: "Target 2:00/500m pace" },
  { week: 2, day: "Thursday", focus: "Active Recovery", main: "30min yoga or mobility work", accessory: null, notes: null },
  { week: 2, day: "Friday", focus: "Functional", main: "50 burpee broad jumps for time, 100 wall balls", accessory: "3x10 box jumps", notes: "Break as needed" },
  { week: 2, day: "Saturday", focus: "Long Run + Carry", main: "10km run with 4x200m farmers carry breaks", accessory: null, notes: "Practice transitions" },
  { week: 2, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 3, day: "Monday", focus: "Tempo Run", main: "3km warmup, 4km tempo at threshold, 2km cooldown", accessory: "Core: 4x(25 bicycle crunches, 15 leg raises)", notes: null },
  { week: 3, day: "Tuesday", focus: "Lower Strength", main: "5x5 back squats, 4x6 front squats, 4x8 step-ups", accessory: "3x15 calf raises, 3x12 leg curls", notes: null },
  { week: 3, day: "Wednesday", focus: "SkiErg + Sled", main: "3x(1000m ski, 100m sled push, 100m sled pull)", accessory: null, notes: "Minimal rest between movements" },
  { week: 3, day: "Thursday", focus: "Active Recovery", main: "40min easy swim or bike", accessory: "Hip mobility work", notes: null },
  { week: 3, day: "Friday", focus: "Burpees + Row", main: "5x(20 burpees, 500m row)", accessory: "3x20 KB swings", notes: "Target under 5min per round" },
  { week: 3, day: "Saturday", focus: "Long Run", main: "12km progressive run (last 4km at tempo)", accessory: null, notes: null },
  { week: 3, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 4, day: "Monday", focus: "Easy Run", main: "5km easy run", accessory: "Light core work", notes: "Deload week" },
  { week: 4, day: "Tuesday", focus: "Light Strength", main: "3x10 bodyweight squats, 3x10 push-ups, 3x10 inverted rows", accessory: "Mobility work", notes: "50% intensity" },
  { week: 4, day: "Wednesday", focus: "Easy Cardio", main: "30min easy bike or elliptical", accessory: "Stretching", notes: null },
  { week: 4, day: "Thursday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },
  { week: 4, day: "Friday", focus: "Light Movement", main: "3km jog, light sled work", accessory: null, notes: null },
  { week: 4, day: "Saturday", focus: "Easy Run", main: "6km easy run", accessory: null, notes: null },
  { week: 4, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 5, day: "Monday", focus: "Speed Work", main: "8x200m sprints with 90s rest", accessory: "Core: 4x(30s hollow hold, 20 mountain climbers)", notes: null },
  { week: 5, day: "Tuesday", focus: "Heavy Strength", main: "5x3 deadlifts, 4x5 weighted lunges, 4x8 hip thrusts", accessory: "3x12 leg press", notes: null },
  { week: 5, day: "Wednesday", focus: "Circuit Simulation", main: "4 rounds: 1km run, 500m ski, 500m row", accessory: null, notes: "Race pace practice" },
  { week: 5, day: "Thursday", focus: "Active Recovery", main: "45min yoga", accessory: null, notes: null },
  { week: 5, day: "Friday", focus: "Wall Balls + Carry", main: "100 wall balls, 400m farmers carry, 100 wall balls", accessory: null, notes: "Break as needed" },
  { week: 5, day: "Saturday", focus: "Long Run", main: "14km at marathon pace", accessory: null, notes: null },
  { week: 5, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 6, day: "Monday", focus: "Interval Run", main: "5x800m at 5K pace with 400m jog recovery", accessory: "Core circuit", notes: null },
  { week: 6, day: "Tuesday", focus: "Full Body", main: "5x5 power cleans, 4x8 push press, 4x10 pull-ups", accessory: "3x15 dips", notes: null },
  { week: 6, day: "Wednesday", focus: "Full Circuit", main: "8 rounds: 1km run + 1 station (rotate through all 8)", accessory: null, notes: "Full circuit simulation" },
  { week: 6, day: "Thursday", focus: "Active Recovery", main: "30min easy swim", accessory: "Foam rolling", notes: null },
  { week: 6, day: "Friday", focus: "Sled + Burpees", main: "5x(100m sled push, 100m sled pull, 20 burpees)", accessory: null, notes: null },
  { week: 6, day: "Saturday", focus: "Race Pace Run", main: "10km at target race pace", accessory: null, notes: null },
  { week: 6, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 7, day: "Monday", focus: "Tempo Run", main: "2km warmup, 5km tempo, 2km cooldown", accessory: "Light core", notes: "Taper begins" },
  { week: 7, day: "Tuesday", focus: "Maintenance Strength", main: "3x5 squats, 3x5 deadlifts at 70%", accessory: null, notes: "Reduce volume" },
  { week: 7, day: "Wednesday", focus: "Light Simulation", main: "4 rounds: 800m run + 250m ski + 250m row", accessory: null, notes: "60% effort" },
  { week: 7, day: "Thursday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },
  { week: 7, day: "Friday", focus: "Easy Movement", main: "Light sled work, 50 wall balls", accessory: null, notes: "Stay loose" },
  { week: 7, day: "Saturday", focus: "Easy Run", main: "8km easy run with strides", accessory: null, notes: null },
  { week: 7, day: "Sunday", focus: "Rest", main: "Complete rest", accessory: null, notes: null },

  { week: 8, day: "Monday", focus: "Shakeout Run", main: "4km easy with 4x100m strides", accessory: null, notes: "Stay fresh" },
  { week: 8, day: "Tuesday", focus: "Light Movement", main: "20min easy bike, light stretching", accessory: null, notes: null },
  { week: 8, day: "Wednesday", focus: "Activation", main: "2km jog, 10 burpees, 250m row, 250m ski", accessory: null, notes: "Keep it light" },
  { week: 8, day: "Thursday", focus: "Rest", main: "Complete rest, hydrate well", accessory: null, notes: "Pre-race prep" },
  { week: 8, day: "Friday", focus: "Rest", main: "Complete rest, carb loading", accessory: null, notes: null },
  { week: 8, day: "Saturday", focus: "RACE DAY", main: "RACE DAY - Give it everything!", accessory: null, notes: "Trust your training!" },
  { week: 8, day: "Sunday", focus: "Recovery", main: "Light walk, celebrate!", accessory: null, notes: "Well done!" },
];
