/**
 * Per-exercise load anchors for plan generation (audit H17/M7 root cause).
 *
 * Plan chunks are generated by PARALLEL model calls, and until this existed no
 * chunk — not even week 1 — received a single absolute load: the only load
 * line in any prompt was one qualitative posture sentence, attached to the
 * week-1 chunk. Every number in a generated plan was invented from "experience
 * level" alone, separately per chunk, so loads could reset at every chunk
 * boundary and the week-over-week ceiling was uninformable at generation time.
 * The downstream clamp catches upward jumps; a chunk that restarts LOWER reads
 * as a deload and ships, so the sawtooth half was uncorrectable anywhere.
 *
 * The fix is deterministic shared state rather than sequenced calls: every
 * chunk receives the SAME per-exercise anchor table, computed from the
 * athlete's own logged history, plus an explicit ramp rule expressed relative
 * to it. Two chunks that never see each other still agree about week 5,
 * because both derive it from the same numbers — continuity by construction,
 * at zero added latency. The clamp remains the hard guarantee.
 *
 * The history this reads was ALREADY fetched by the posture computation and
 * used only for one mood sentence — the same shape as the deload finding,
 * where the data needed was being paid for and discarded.
 */

import {
  convertWeight,
  roundStoredWeight,
  standardizeWeightUnit,
  type WeightUnit,
} from "@shared/unitConversion";

import type { LoggedExerciseSetWithDate } from "../storage/shared";

/** Median top-set weight for one exercise, in the athlete's display unit. */
export interface LoadAnchor {
  /** Analytics' exercise key: `exerciseName`, or `custom:<label>` (audit H4). */
  readonly exercise: string;
  readonly weight: number;
  /** Distinct training days behind the number — the evidence count. */
  readonly sessions: number;
}

/** Fewer sessions than this is one data-entry error away from a bad anchor. */
const MIN_SESSIONS = 2;
/** Enough exercises to anchor a HYROX strength programme; more is prompt noise. */
const MAX_ANCHORS = 8;

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid];
}

/**
 * The athlete's recent working weights, one anchor per exercise.
 *
 * Two aggregation choices carry the correctness:
 *
 * - Per DAY, the top set — warm-up and working sets of one lift are separate
 *   rows spanning a 2.3x range within a single session (the same spread that
 *   forced the unit-switch detector onto daily medians), and "what the athlete
 *   squats" is the top of that range, not its average.
 * - Across days, the MEDIAN of those tops — robust to the one day they tested
 *   a heavy single and to the one day they deloaded, where a mean is dragged
 *   by both.
 *
 * Weights are read through the row's own unit stamp with the athlete's current
 * preference as the legacy fallback — the exact contract `storedWeightToKg`
 * uses (audit L4) — and reported in the display unit the prompt already
 * declares.
 */
export function buildLoadAnchors(
  sets: readonly LoggedExerciseSetWithDate[],
  displayUnit: WeightUnit,
): LoadAnchor[] {
  // exercise -> date -> top weight that day, in display units.
  const topByDay = new Map<string, Map<string, number>>();
  for (const set of sets) {
    if (set.weight == null || set.weight <= 0 || (set.reps ?? 0) <= 0) continue;
    const key =
      set.exerciseName === "custom" && set.customLabel
        ? `custom:${set.customLabel}`
        : set.exerciseName;
    const storedUnit = standardizeWeightUnit(set.weightUnit ?? displayUnit);
    const weight = convertWeight(set.weight, storedUnit, displayUnit);

    let byDate = topByDay.get(key);
    if (!byDate) {
      byDate = new Map<string, number>();
      topByDay.set(key, byDate);
    }
    const top = byDate.get(set.date);
    if (top == null || weight > top) byDate.set(set.date, weight);
  }

  const anchors: LoadAnchor[] = [];
  for (const [exercise, byDate] of topByDay) {
    if (byDate.size < MIN_SESSIONS) continue;
    anchors.push({
      exercise,
      weight: roundStoredWeight(median([...byDate.values()]), displayUnit),
      sessions: byDate.size,
    });
  }

  // Most-practised first — those are the lifts the plan will actually
  // prescribe — with weight as the tiebreak so the order is deterministic.
  anchors.sort((a, b) => b.sessions - a.sessions || b.weight - a.weight);
  return anchors.slice(0, MAX_ANCHORS);
}

/**
 * The prompt block that makes the ceiling enforceable at generation time.
 *
 * Every chunk receives these SAME lines. The ramp is stated relative to the
 * anchors ("week k of a build ≈ anchor × 1.025^(k-1)") rather than to the
 * previous week's output, precisely because no chunk can see another's output
 * — a rule each call can evaluate alone is the only kind parallel generation
 * can obey. Deloads and tapers stay free to go below the line: the anchors pin
 * the reference trajectory, not a floor.
 */
export function describeLoadAnchorLines(
  anchors: readonly LoadAnchor[],
  displayUnit: WeightUnit,
): string[] {
  if (anchors.length === 0) return [];
  return [
    ``,
    `RECENT WORKING WEIGHTS (median top set from the athlete's own logs):`,
    ...anchors.map((a) => `- ${a.exercise}: ${a.weight} ${displayUnit} (${a.sessions} sessions)`),
    `Anchor every prescribed load to these numbers: treat them as week-1 working weights, and apply each phase's weekly progression RELATIVE to them — during a build, week k sits near anchor × 1.025^(k-1) and never above anchor × 1.05^(k-1). Every chunk of this plan receives these same anchors, so week-to-week loads must stay continuous with the weeks you are not generating. Deload and taper weeks go below the line as usual. For exercises not listed, prescribe loads consistent with these anchors.`,
  ];
}
