/**
 * The skeleton every chunk of a generated plan shares: which phase each week
 * is in, which weeks deload, how the weeks group into training blocks, and the
 * primary lifts that run through all of them.
 *
 * Plan chunks are generated by PARALLEL model calls (planGenerationService),
 * so anything two chunks must agree on has to be decided before either call
 * starts — the reasoning that already gave every chunk the same load anchors
 * (loadAnchors.ts). Left to the model, the chunks of one plan each guessed
 * where "a deload at ~50%" fell, so a boundary could get two deload weeks or
 * none; each picked its own squat variation, so the plan changed exercise at
 * every chunk boundary and no load could progress across it; and each drew
 * its phase lines by its own reading of "the first 25%", not by
 * computePlanPhase, which is the rule the in-app coach later reviews those
 * same weeks with.
 */
import type { TrainingPhase } from "@shared/nutritionTargets";
import { computePlanPhase, formatPhaseName } from "@shared/planPhase";

import { formatPrimaryLifts } from "../prompts/exerciseSelection";
import type { PrimaryLift } from "./ai/exerciseSelection";

export interface PlanWeekOutline {
  readonly week: number;
  readonly phase: TrainingPhase;
  readonly deload: boolean;
  /** 1-based training block; a new block starts the week after a deload. */
  readonly block: number;
}

/** Shorter plans are one block: a deload would be a tenth of the plan or more. */
const MIN_WEEKS_FOR_DELOAD = 6;
/** From here on a single deload no longer covers the plan; deload every 4th week. */
const LONG_PLAN_WEEKS = 12;
const DELOAD_INTERVAL_WEEKS = 4;
/**
 * The final weeks unload anyway (taper, then race week), so a deload right
 * before them would stack three easy weeks at the end of the plan.
 */
const FINAL_WEEKS_WITHOUT_DELOAD = 3;
/** Below this a non-race plan is too short to periodise. */
const MIN_WEEKS_FOR_PHASES_WITHOUT_RACE = 4;

/**
 * The deload weeks for a plan. Plans up to 11 weeks keep the single deload at
 * ~50% the generator has always asked for; longer plans deload every 4th week,
 * because one deload in 24 weeks is not a programme anyone would write by hand.
 */
export function planDeloadWeeks(totalWeeks: number): number[] {
  if (totalWeeks < MIN_WEEKS_FOR_DELOAD) return [];
  if (totalWeeks < LONG_PLAN_WEEKS) return [Math.round(totalWeeks / 2)];
  const weeks: number[] = [];
  for (
    let week = DELOAD_INTERVAL_WEEKS;
    week <= totalWeeks - FINAL_WEEKS_WITHOUT_DELOAD;
    week += DELOAD_INTERVAL_WEEKS
  ) {
    weeks.push(week);
  }
  return weeks;
}

export function buildPlanOutline(totalWeeks: number): PlanWeekOutline[] {
  const deloads = new Set(planDeloadWeeks(totalWeeks));
  const outline: PlanWeekOutline[] = [];
  let block = 1;
  for (let week = 1; week <= totalWeeks; week++) {
    const phase = computePlanPhase(totalWeeks, week)?.phaseLabel ?? "early";
    const deload = deloads.has(week);
    outline.push({ week, phase, deload, block });
    if (deload) block += 1;
  }
  return outline;
}

function describeBlocks(outline: readonly PlanWeekOutline[]): string | null {
  const ranges = new Map<number, { first: number; last: number }>();
  for (const { week, block } of outline) {
    const range = ranges.get(block);
    if (range) range.last = week;
    else ranges.set(block, { first: week, last: week });
  }
  if (ranges.size < 2) return null;
  const spans = [...ranges.entries()].map(([block, { first, last }]) =>
    first === last ? `week ${first} = block ${block}` : `weeks ${first}-${last} = block ${block}`,
  );
  return `- Blocks: ${spans.join(" · ")}. Inside a block keep the same exercises week to week and progress them; when a new block starts, rotate one or two ACCESSORY exercises (to a close variation, or to a need from the EXERCISE SELECTION BRIEF). Primary lifts never rotate.`;
}

function weekLabel(entry: PlanWeekOutline, totalWeeks: number, hasRace: boolean): string {
  const isFinal = entry.week === totalWeeks;
  const phase = isFinal && !hasRace ? "FINAL WEEK" : formatPhaseName(entry.phase).toUpperCase();
  const deload = entry.deload ? ", DELOAD" : "";
  return `week ${entry.week} = ${phase}${deload} (block ${entry.block})`;
}

export interface BlueprintChunk {
  readonly startWeek: number;
  readonly endWeek: number;
}

/**
 * The PROGRAM BLUEPRINT block for one chunk. Every chunk receives the same
 * block layout and primary lifts; only the week lines are its own.
 */
export function describeProgramBlueprintLines(input: {
  readonly totalWeeks: number;
  readonly range: BlueprintChunk;
  readonly hasRace: boolean;
  readonly primaryLifts: readonly PrimaryLift[];
  /** The WORKOUT ENGINE TARGETS block follows with the lifts' exact numbers. */
  readonly hasEngineTargets?: boolean;
}): string[] {
  const { totalWeeks, range, hasRace, primaryLifts } = input;
  const outline = buildPlanOutline(totalWeeks);
  const showPhases = hasRace || totalWeeks >= MIN_WEEKS_FOR_PHASES_WITHOUT_RACE;
  const chunkWeeks = outline.filter(
    (entry) => entry.week >= range.startWeek && entry.week <= range.endWeek,
  );

  const lines = [
    "",
    "PROGRAM BLUEPRINT (identical in every chunk of this plan — follow it exactly, so the whole plan reads as one programme):",
  ];
  const blocks = describeBlocks(outline);
  if (blocks) lines.push(blocks);
  if (primaryLifts.length > 0) {
    const progression = input.hasEngineTargets
      ? "at exactly the sets, reps and loads the WORKOUT ENGINE TARGETS give for each week"
      : "and progress them against RECENT WORKING WEIGHTS when listed";
    lines.push(
      `- Primary lifts for the whole plan: ${formatPrimaryLifts(primaryLifts)}. Use these exact exercises (not look-alikes) every week that includes strength work, ${progression}.`,
    );
  }
  if (showPhases) {
    lines.push(
      `- Weeks in this chunk (the same phases the in-app coach will review them by): ${chunkWeeks
        .map((entry) => weekLabel(entry, totalWeeks, hasRace))
        .join("; ")}.`,
    );
  }
  if (chunkWeeks.some((entry) => entry.deload)) {
    lines.push(
      "- DELOAD week: keep the same exercises and session structure, cut sets by about half, loads ~10% lighter, no max efforts or tests. Program no other deload weeks.",
    );
  }
  if (showPhases && !hasRace && chunkWeeks.some((entry) => entry.week === totalWeeks)) {
    lines.push(
      "- FINAL WEEK: the in-app coach reviews a plan's last week as a taper, so keep it light — shorter sessions, sharp not tiring; a short benchmark or retest session fits well.",
    );
  }
  return lines;
}
